[tool.poetry]
name = "myong"
version = "0.1.0"
description = ""
<<<<<<< HEAD
authors = ["Darío Ureña <darioaxel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.2.7"
psycopg2-binary = "^2.9.11"
python-decouple = "^3.8"
django-crispy-forms = "^2.5"
crispy-bootstrap5 = "^2025.6"
=======
authors = ["rhernandezmy <rhernandezmy@fpvirtualaragon.es>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = ">=5.1,<6.0"
python-decouple = "^3.8"
django-crispy-forms = "^2.5"
crispy-bootstrap5 = "^2025.6"
psycopg = {extras = ["binary"], version = "^3.3.2"}
>>>>>>> myorigin/main

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
